name = "minecraft-pack-1201"
author = "CrystalysGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5351d03e56c1b80240610d2cc1b8d1c6c3f8da73caaf2eac97b1ed1a8781687c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
