name = "minecraft-pack-1201"
author = "CrystalysGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b559b272799cea9d652d6a537cec17f01f51980fbc72dbf6a2542b3246bf7c23"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
