name = "minecraft-pack-1201"
author = "CrystalysGolem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60487cfdbeb1915c5f06c274cf973a045c286139e837ec0cea49b703ec766caf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
