#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 30 21:54:11 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=ComplementaryReimagined_r5.9.zip
enableShaders=true
