#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Sep 15 04:20:43 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.9.zip
enableShaders=true
